default_language_version:
  python: python3.11
  
repos:
-   repo: https://github.com/pycqa/flake8
    rev: ''
    hooks:
    -   id: flake8

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''
    hooks:
    -   id: mypy
