name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  run_style:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Set up python
        uses: actions/setup-python@v6.0.0
        with:
          python-version-file: '.python-version'

      - name: Install dependencies
        run: make install-all

      - name: Check style
        run: make style

  run_types:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Set up python
        uses: actions/setup-python@v6.0.0
        with:
          python-version-file: '.python-version'

      - name: Install dependencies
        run: make install-all

      - name: Check types
        run: make types

  run_tests:
    runs-on: [ubuntu-latest]
    needs: [run_style, run_types]
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Set up python
        uses: actions/setup-python@v6.0.0
        with:
          python-version-file: '.python-version'
      
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0.3
        with:
          # The directory to put the envfile in
          directory: cleanhub
          
      - name: Install dependencies
        run: make install-all

      - name: Run tests
        run: make tests
